In [1]:
!pip install tensorflow

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
tf.__version__

'2.15.0'

In [4]:
#Create two tensors

tensor1 = tf.constant([[1,2], [3,4]])
tensor2 = tf.constant([[5,6], [7,8]])

In [5]:
# Perform Addition

addition_Result = tf.add(tensor1, tensor2)
addition_Result

<tf.Tensor 'Add:0' shape=(2, 2) dtype=int32>

In [6]:
#Perform Multiplication

multiplication_Result = tf.multiply(tensor1,tensor2)

In [7]:
#Start a tensor flow session

with tf.Session() as sess:

  #Run the operation

  addition_output, multiplication_output = sess.run([addition_Result, multiplication_Result])
  print("Addition Result: ")
  print(addition_output)

  print("Multiplication Result: ")
  print(multiplication_output)

Addition Result: 
[[ 6  8]
 [10 12]]
Multiplication Result: 
[[ 5 12]
 [21 32]]


In [8]:
import tensorflow as tf

In [9]:
#Create two tensors

tensor1 = tf.constant([[1,2], [3,4]])
tensor2 = tf.constant([[5,6], [7,8]])

In [10]:
# Perform Addition

addition_Result = tf.add(tensor1, tensor2)
addition_Result

<tf.Tensor 'Add_1:0' shape=(2, 2) dtype=int32>

In [11]:
#Perform Multiplication

multiplication_Result = tf.multiply(tensor1,tensor2)
multiplication_Result

<tf.Tensor 'Mul_1:0' shape=(2, 2) dtype=int32>

In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Create two tensors
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Perform Addition
addition_Result = tf.add(tensor1, tensor2)

# Perform Multiplication
multiplication_Result = tf.multiply(tensor1, tensor2)

# Start a TensorFlow session
with tf.Session() as sess:
    # Run the operations
    addition_output, multiplication_output = sess.run([addition_Result, multiplication_Result])
    print("Addition Result:")
    print(addition_output)
    print("Multiplication Result:")
    print(multiplication_output)


Addition Result:
[[ 6  8]
 [10 12]]
Multiplication Result:
[[ 5 12]
 [21 32]]


In [13]:
#Create a basic matrix

x = tf.ones((3,3))
print(x)

Tensor("ones:0", shape=(3, 3), dtype=float32)


In [14]:
x = tf.zeros((3,3))
print(x)

Tensor("zeros:0", shape=(3, 3), dtype=float32)


In [15]:
x = tf.eye((3))
print(x)

Tensor("eye/diag:0", shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.normal((3,3), mean = 0,stddev = 1)
print(x)

Tensor("random_normal:0", shape=(3, 3), dtype=float32)


In [17]:
x = tf.random.uniform((3,3), minval = 0,maxval = 1)
print(x)

Tensor("random_uniform/RandomUniform:0", shape=(3, 3), dtype=float32)


In [18]:
x = tf.range(start=1, limit = 10, delta = 2)
print(x)

Tensor("range:0", shape=(5,), dtype=int32)


In [19]:
x =  tf.cast(x,dtype = tf.float32)
x

<tf.Tensor 'Cast:0' shape=(5,) dtype=float32>

In [20]:
x  = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(x)
print(x.shape)
print(x.dtype)

Tensor("Const_6:0", shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [21]:
#addition
print(x + x)

Tensor("add_3:0", shape=(2, 3), dtype=float32)


In [22]:
#addition
tf.add(x,x)

<tf.Tensor 'Add_4:0' shape=(2, 3) dtype=float32>

In [23]:
#Subtraction
tf.subtract(x,x)

<tf.Tensor 'Sub:0' shape=(2, 3) dtype=float32>

In [24]:
#Multiplication
print(x*x)

print(5*x)

Tensor("mul_3:0", shape=(2, 3), dtype=float32)
Tensor("mul_4:0", shape=(2, 3), dtype=float32)


In [25]:
tf.multiply(x,x)

<tf.Tensor 'Mul_5:0' shape=(2, 3) dtype=float32>

In [26]:
#Divide

x/x


<tf.Tensor 'truediv:0' shape=(2, 3) dtype=float32>

In [27]:
#Divide

tf.divide(x,x)

<tf.Tensor 'truediv_1:0' shape=(2, 3) dtype=float32>

In [28]:
#Power
x**4

<tf.Tensor 'pow:0' shape=(2, 3) dtype=float32>

In [29]:
#Reshape x to have a shape of(3,2)

y = tf.reshape(x,[3,2])

#Calculate tensor dot product
z = tf.tensordot(x,y,axes = 1)


#print result
print(z)
print(y)

Tensor("Tensordot/MatMul:0", shape=(2, 2), dtype=float32)
Tensor("Reshape:0", shape=(3, 2), dtype=float32)


In [30]:
#2nd method of matrix multiplication using tf.matmul()
z = tf.matmul(x,y)
z

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>

In [31]:
#3rd method of matrix multiplication using @

x @ y

<tf.Tensor 'matmul_1:0' shape=(2, 2) dtype=float32>

In [32]:
x @ tf.transpose(x)

<tf.Tensor 'matmul_2:0' shape=(2, 2) dtype=float32>

In [33]:
tf.concat([x,x,x], axis = 0)

<tf.Tensor 'concat:0' shape=(6, 3) dtype=float32>

In [34]:
tf.nn.softmax(x, axis = -1) # nn = neural network    and softmax = activation function

<tf.Tensor 'Softmax:0' shape=(2, 3) dtype=float32>

In [35]:
#sum of tensorflow
tf.reduce_sum(x)

<tf.Tensor 'Sum:0' shape=() dtype=float32>

In [36]:
#convert vector to tensor

z = tf.convert_to_tensor([0,1,2,3,4,5,6,7,8,9])
z

<tf.Tensor 'Const_8:0' shape=(10,) dtype=int32>

In [37]:
#slicing and indexing
print(z[:])
print(z[1:])
print(z[1:3])
print(z[::3])
print(z[::-1])

Tensor("strided_slice:0", shape=(10,), dtype=int32)
Tensor("strided_slice_1:0", shape=(9,), dtype=int32)
Tensor("strided_slice_2:0", shape=(2,), dtype=int32)
Tensor("strided_slice_3:0", shape=(4,), dtype=int32)
Tensor("strided_slice_4:0", shape=(10,), dtype=int32)


In [38]:
#if we want random positon number like we want 0th,3rd,7th element

indices = tf.constant([0,3,7])
z_ind = tf.gather(z, indices)
print(z_ind)

Tensor("GatherV2:0", shape=(3,), dtype=int32)


In [39]:
tf.reduce_sum([1,2,3])

<tf.Tensor 'Sum_1:0' shape=() dtype=int32>

In [40]:
z = tf.range(9)
print(z)
z = tf.reshape(z,(3,3))
print(z)

Tensor("range_2:0", shape=(9,), dtype=int32)
Tensor("Reshape_1:0", shape=(3, 3), dtype=int32)


### Advance level


In [41]:
#WHICH DEVICE IS USED BY TENSORFLOW FOR EXECUTION

if tf.config.list_physical_devices('GPU'):
  print("TEnsor flow is using GPU")
else:
  print("Not using GPU")

Not using GPU


In [42]:
if tf.config.list_physical_devices('CPU'):
  print("TEnsor flow is using CPU")
else:
  print("Not using CPU")

TEnsor flow is using CPU


In [43]:
if tf.config.list_physical_devices('TPU'):
  print("TEnsor flow is using TPU")
else:
  print("Not using TPU")

Not using TPU


In [44]:
##

var = tf.Variable([0.0,0.0,0.0])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32_ref>


In [45]:
#

var.assign([1,2,3])

<tf.Tensor 'Assign:0' shape=(3,) dtype=float32_ref>

In [46]:
var.assign_add([1,1,1])

<tf.Tensor 'AssignAdd:0' shape=(3,) dtype=float32_ref>

In [47]:
#Creating function

x = tf.Variable(1.0)

def func(x):
   y = x**2 + 2*x - 5
   return y

In [48]:
func(x)

<tf.Tensor 'sub_1:0' shape=() dtype=float32>